### ISSUE TITLE
why your left join is so fast ? 

### ISSUE THREAD

**Issue by dridk** [vatlab/VariantTools#14]
I tried to make annotation using postgreSQL like vtools do. 
I wonder why vtools is so fast when I perform a selection on dbNSFP which is a huge database. 
What was your improvement ? 
I see you use UCSC binning and indexing. Are you using other improvement ?

**Comment by BoPeng** [comment]
vtools tries really hard to improve performance but essentially speaking sqlite operates locally and is much faster than a client/server architecture such as postgreSQL. We actually had a mySQL backend before the 1.0 release but we decided to drop it because it was at least 5 times slower than sqlite and while we could optimize content layout (paging) and sqlite engine to achieve better performance, we could not do anything to the mySQL engine.

On the SQL side, we used binning and indexing and some complex SQL scheme for range based queries. You could use the `-v` option to display the actual SQL if you are interested.
