### ISSUE TITLE
Export then Import via Vcf Format

### ISSUE THREAD

**Issue by andytokens** [vatlab/VariantTools#3]
I tried to export from a vtools project using the following command:

`vtools export variants_for_course --format vcf --samples "selected=\"Yes\"" --header CHROM POS ID REF ALT QUAL FILTER INFO FORMAT '%(sample_names)s' -o my.vcf`

then I move the file to a different folder and import into another vtools project
`vtools import --format vcf my.vcf --build hg19`
I got this warning

> WARNING: Cannot import genotype from the input file: Failed to guess sample name. Please specify sample names for 3000 samples using parameter --sample_name, or add a proper header to your input file that matches the columns of samples. See "vtools import -h" for details.

I tried add "#" to the header in the vcf file, but still doesn't work

> INFO: 0 new variants  from 0 lines are imported.

**Comment by gaow** [comment]
It does look from the export command that the header should contain sample names due to `--header ... %(sample_names)` in `vtools export`. Does your VCF file contains the header line as expected (does it start with with `#CHROM POS ...`)?

**Comment by andytokens** [comment]
`vtools export variants_for_course --format vcf --samples "selected=\"Yes\"" --header CHROM POS ID REF ALT QUAL FILTER INFO FORMAT '%(sample_names)s' -o my.vcf`
`head my.vcf`

> CHROM POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  110051  110052  110053 ...
> 21 10862599    .   C   T   .   PASS    .       0/1 0/1 0/1 ...

The first line is "CHROM POS", but not starting "#". Also the number of column in the header doesn't match the number of column in the other rows.

`head -1 my.vcf | wc`

> 1    3009   27045

`head -2 my.vcf | tail -1 | wc`

> 1    3008   10888

**Comment by gaow** [comment]
Somehow the exported data is problematic ... it's one column off, missing `FORMAT` string. Your data should look like

```
21 10862599 . C T . PASS . GT 0/1 0/1 0/1 ...
```

currently it is missing `GT`.

It is our undoing because in `vcf.fmt` we had `format_string` related entries empty. We should have used a default string `GT` for it. 

It is possible to change `format_string` related entries in `vcf.fmt` and re-export but that will be a waste. Instead, could you try:
1. Add `#` to the header
2. remove `FORMAT` from the header, and in your `[GT]` section of `vcf.fmt` change `index=10:` to `index=9:`, and import the data? Basically you `cp ~/.variant_tools/format/vcf.fmt modified_vcf.fmt`, edit `modified_vcf.fmt` and `vtools import --format modified_vcf.fmt my.vcf --build hg19`
