### ISSUE TITLE
Conda release of vtools 3.0 beta

### ISSUE THREAD

**Issue by BoPeng** [vatlab/VariantTools#80]
Should we wait for a more stable version of vtools before we make a binary release for conda, or should we go ahead and release 3.0 beta for conda now?

**Comment by gaow** [comment]
Well, my #79 issue is not just about slowness. There are still non-pipeline related commands that do not run for the new genotype DB when I tried earlier this morning. Not sure if it is reproducible on your end. I guess it would be good to fix that. Would be even better to look into the performance issue, because otherwise it would be very difficult to operate over genotypes. 

I noticed pypi still has version 2.7 and I take that it is intentional -- prevent users from `pip install` to the unstable version? Or we can make it under a different package name?

**Comment by BoPeng** [comment]
Yes we could release vtools under the name of vat.

**Comment by gaow** [comment]
I was just testing out this on a docker image: 

```
conda install -c https://conda.binstar.org/bpeng variant_tools 
```

it does not completely work unless i also add 

```
conda install scipy pytables
```

in the docker file. Can we include `scipy` and `pytables` in the conda recipe for vtools?

**Comment by gaow** [comment]
@jma7 current release is version 3.0.2 on conda which is a version behind. It would be great if we can release a new version there. But I'm in the process of testing the new version on this tutorial:

https://gaow.github.io/ismb-2018/

I hope all works -- right now it is just extremely slow loading the genotypes. My test image is a virtual machine of 2GB memory and 1 CPU

http://149.28.122.251/vat.html

(the `vtools import` command is very slow, to begin with.)
